

TYPE_OUTPUT_HTML = "HTML"
TYPE_OUTPUT_PDF = "PDF"
TYPE_OUTPUT_XLS = "XLS"
TYPE_OUTPUT_RTF = "RTF"
TYPE_OUTPUT_CSV = "CSV"
TYPE_OUTPUT_ODS = "ODS"
TYPE_OUTPUT_ODT = "ODT"
TYPE_OUTPUT_DOCX = "DOCX"
TYPE_OUTPUT_XLSX = "XLSX"
TYPE_OUTPUT_JPRINT = "JPRINT"
TYPE_OUTPUT_XML = "XML"